baseURL = 'https://emsimons.github.io/me/'
languageCode = 'en-us'
title = 'Emily M. Simons'
theme = 'papermod'
enableEmoji = true

[menu]
  [[menu.main]]
  identifier = "CV"
  name = "CV"
  url = "/files/emily-simons-cv.pdf"
  weight = 1

  [[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.assets]
  customCSS = ["css/custom.css"]