baseURL = 'https://emsimons.github.io/me/'
languageCode = 'en-us'
title = 'Emily M. Simons'
theme = 'papermod'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'